### ISSUE TITLE
下拉过程中的时候，加载中不显示

### ISSUE THREAD

**Issue by zhongku** [yangqihua/vue-scroll-mobile-demo#1]
![default](https://user-images.githubusercontent.com/16175495/35494084-077a4c0a-04f3-11e8-95f4-2a74b05cdd7a.png)

**Comment by zhongku** [comment]
![default](https://user-images.githubusercontent.com/16175495/35494102-28b2b592-04f3-11e8-87ce-0337f89c35df.png)
这里是代码

**Comment by yangqihua** [comment]
请在 <scroll></scroll>标签中务必配置好warpId，如：
```
<scroll class="scroller" :upCallback="upCallback" ref="mescroll" warpId="index_scroll" id="index_scroll">
```

**Comment by mhxy13867806343** [comment]
出现和你一样的情况，你怎么解决的？
