### ISSUE TITLE
vue-infinite-loading好像不支持横向scroll

### ISSUE THREAD

**Issue by s-sevenup** [yangqihua/vue-scroll-mobile-demo#2]
看你的介绍说，vue-infinite-loading支持横向scroll，请问怎么实现

**Comment by yangqihua** [comment]
横向的话用 better-scroll 就好了，因为横向的数据量不会很多

**Comment by s-sevenup** [comment]
嗯！目前我就是这样，但是不想引用两个，如果是移动端的还好解决，项目是pc，不知道有什么解决办法

**Comment by yangqihua** [comment]
那你不一定要用vue-infinite-loading啊，可以自己去实现一线横向的原生的方法去实现
